// /src/models/career/roadmap.model.ts
import mongoose, { Schema, Document } from "mongoose";

export enum RoadmapType {
  SHORT_TERM = "SHORT_TERM",
  MEDIUM_TERM = "MEDIUM_TERM",
  LONG_TERM = "LONG_TERM",
}

export interface IRoadmap extends Document {
  studentId: mongoose.Types.ObjectId;
  title: string;
  careerGoal: string;
  type: RoadmapType;
  durationMonths: number;
  startDate: Date;
  expectedCompletion: Date;
  isAutoGenerated: boolean;
  generationModel: string;
  completionPercentage: number;
  completedMilestones: number;
  totalMilestones: number;

  // Références
  phases: mongoose.Types.ObjectId[];
}

const roadmapSchema = new Schema<IRoadmap>(
  {
    studentId: {
      type: Schema.Types.ObjectId,
      ref: "Student",
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    careerGoal: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      enum: Object.values(RoadmapType),
      required: true,
    },
    durationMonths: {
      type: Number,
      required: true,
      min: 1,
    },
    startDate: {
      type: Date,
      default: Date.now,
    },
    expectedCompletion: {
      type: Date,
      required: true,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    generationModel: {
      type: String,
    },
    completionPercentage: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    completedMilestones: {
      type: Number,
      default: 0,
      min: 0,
    },
    totalMilestones: {
      type: Number,
      default: 0,
      min: 0,
    },
    phases: [
      {
        type: Schema.Types.ObjectId,
        ref: "RoadmapPhase",
      },
    ],
  },
  {
    timestamps: true,
    collection: "roadmaps",
  },
);

// Index
roadmapSchema.index({ studentId: 1, type: 1 });
roadmapSchema.index({ careerGoal: "text", title: "text" });
roadmapSchema.index({ expectedCompletion: 1 });
roadmapSchema.index({ completionPercentage: -1 });

export const Roadmap = mongoose.model<IRoadmap>("Roadmap", roadmapSchema);
